"use client";
import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from './components/navigation/Navigation'
import { Footer } from './components/footer/Footer'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'La Pucelle',
  description: 'Generated by create next app',
}

function Loading(){
  const router = useRouter()
  const[loading, setLoading] = useState(false)
  useEffect(() => {
    const handleStart = (url) => (url !== router.asPath) && setLoading(true)
    const handleComplete = (url) => (url === router.asPath) && setTimeout(() => {setLoading(false)}, 5000)

    router.events.on('routeChangeStart', handleStart)
    router.events.on('routeChangeComplete', handleComplete)
    router.events.on('routeChangeError', handleComplete)

    return () =>{
      router.events.off('routeChangeStart', handleStart)
      router.events.off('routeChangeComplete', handleComplete)
      router.events.off('routeChangeError', handleComplete)
    }
  })
  return loading && (
    <div>hola toy cargando :v</div>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Loading />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
