import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from './components/navigation/Navigation'
import { DayNight } from './components/day-night/DayNight'
import { Footer } from './components/footer/Footer'
import { Loading } from './components/loading/Loading'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'La Pucelle',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Suspense fallback={ <Loading /> }>
        <body className={inter.className}>
          <Navigation />
          <DayNight />
          {children}
          <Footer />
        </body>
      </Suspense>
    </html>
  )
}
