export const metadata = {
    title: 'La Pucelle | Portfolio  ',
    description: 'Generated by create next app',
}

function onBlur() {
    document.title = 'Hey! Come Back!'
}

function onFocus() {
  document.title = metadata.title
}

window.addEventListener('blur', onBlur)
window.addEventListener('focus', onFocus)

document.title = metadata.title

export function setTitle(newTitle) {
  metadata.title = newTitle;
  document.title = newTitle;
}