export const metadata = {
  title: 'La Pucelle | Portfolio  ',
  description: 'Generated by create next app',
};

export function onBlur() {
  document.title = 'Hey! Come Back!';
}

export function onFocus() {
  document.title = metadata.title;
}

export function setTitle(newTitle) {
  metadata.title = newTitle;
  if (typeof document !== 'undefined') {
    document.title = newTitle;
  }
}
